routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'VideoSelectionController@chooseNickname')->name('nickname_show');

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::get('/form', 'VideoSelectionController@getFormPart1')->name('form_show');
Route::post('/form', 'VideoSelectionController@getFormPart2')->name('form_send');
Route::get('/win/{id}', 'VideoSelectionController@getFormPart3')->name('winform_show');
Route::post('/win/{id}', 'VideoSelectionController@submitFormPart3')->name('winform_send');
Route::post('/moment', 'VideoSelectionController@chooseMoment')->name('moment_show');
Route::post('/video', 'VideoSelectionController@getVideo')->name('video_get');
Route::get('/video/{id}', 'VideoSelectionController@showVideo')->name('video_show');
Route::get('/video_request', 'VideoSelectionController@getVideoRequest')->name('video_request_show');
Route::get('/preview/{id}', 'VideoSelectionController@getVideoPreview')->name('preview_show');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::resource('/videos', 'VideoController');
Route::resource('/moments', 'MomentController');
Route::resource('/nicknames', 'NicknameController');
Route::resource('/users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    const ROLE_USER = 1;
    const ROLE_MODERATOR = 2;
    const ROLE_ADMINISTRATOR = 3;
    const ROLE_SUPER_ADMINISTRATOR = 4;

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRoleNameAttribute()
    {
        switch ($this->role){
            case User::ROLE_USER:
                return "User";
                break;
            case User::ROLE_MODERATOR:
                return "Moderator";
                break;
            case User::ROLE_ADMINISTRATOR:
                return "Administrator";
                break;
            default:
                return "Super Administrator";
        }
    }

    public function social()
    {
        return $this->hasOne(SocialAccount::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255|unique:users',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => [
                'required',
                'confirmed',
                'min:8',
                'regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\X])(?=.*[!$#%]).*$/',
            ],
            'role' => 'required|digits:1',
        ]);

        $user = new User();
        $user->username = $request->username;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->role = $request->role;
        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('users.edit')->with('user', Auth::user());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->id == $id){
            $error = null;
            $this->validate($request, [
                'name' => 'required|string|max:255',
                'old_password' => 'required|string|max:255',
                'password' => [
                    'nullable',
                    'confirmed',
                    'min:8',
                    'regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\X])(?=.*[!$#%]).*$/',
                ]
            ]);
            $u = User::find($id);
            if (!Auth::attempt(["username" => $u->username, "password" => $request->old_password]))
                return view('users.edit')->withErrors(['error' => "Password is incorrect"])->with('user', $u);

            $u->name = $request->name;
            if(!is_null($request->password)) {
                $u->password = bcrypt($request->password);
            }
            $u->save();
        }else {
            // Auth verif

            $u = User::find($id);
            $u->role = $request->role;
            $u->save();
        }
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        /*
        $u = User::find($id);
        $u->social->delete();
        $u->delete();
         */
        return redirect()->route('users.index');
    }
}

resources/views/users/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <form class="col" action="{{route('users.store')}}" method="post">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {{csrf_field()}}
        <div class="form-group row">
            <label class="col-2 col-form-label" for="name">Name</label>
            <div class="col-10">
                <input type="text" id="name" name="name" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label" for="username">Username</label>
            <div class="col-10">
                <input type="text" id="username" name="username" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-2 col-form-label">E-mail</label>
            <div class="col-10">
                <input type="email" id="email" name="email" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="password" class="col-2 col-form-label">Password</label>
            <div class="col-10">
                <input type="password" id="password" name="password" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="password_confirmation" class="col-2 col-form-label">Confirm password</label>
            <div class="col-10">
                <input type="password" id="password_confirmation" name="password_confirmation" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="role" class="col-2 col-form-label">Role</label>
            <div class="col-10">
                <select name="role" id="role" class="form-control" required>
                    <option value="{{\App\User::ROLE_MODERATOR}}">Moderator</option>
                    <option value="{{\App\User::ROLE_ADMINISTRATOR}}">Administrator</option>
                    <option value="{{\App\User::ROLE_SUPER_ADMINISTRATOR}}">Super Administrator</option>
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <form class="col" action="{{route('users.update', $user->id)}}" method="post">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {{csrf_field()}}
        {{ method_field('PUT')}}
        <div class="form-group row">
            <label class="col-2 col-form-label" for="name">Name</label>
            <div class="col-10">
                <input type="text" id="name" name="name" value="{{$user->name}}" class="form-control" required>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label" for="username">Username</label>
            <div class="col-10">
                {{$user->username}}
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-2 col-form-label">E-mail</label>
            <div class="col-10">
                {{$user->email}}
            </div>
        </div>
        <div class="form-group row">
            <label for="old_password" class="col-2 col-form-label">Old Password</label>
            <div class="col-10">
                <input type="password" id="old_password" name="old_password" class="form-control" required>
            </div>
        </div>
        <div class="row"><h2>Change Password</h2></div>
        <div class="form-group row">
            <label for="password" class="col-2 col-form-label">Password</label>
            <div class="col-10">
                <input type="password" id="password" name="password" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label for="password_confirmation" class="col-2 col-form-label">Confirm password</label>
            <div class="col-10">
                <input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
            </div>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard')

@section('content')
        <div class="col-md-12">
            <h2>Administrators:</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>E-mail</th>
                    <th>Role</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    @if($user->role > \App\User::ROLE_USER)
                    <tr>
                        <th scope="row">{{$user->id}}</th>
                        <td>{{$user->name}}</td>
                        <td>{{$user->username}}</td>
                        <td>{{$user->email}}</td>
                        <td>
                            @if($user->id != Auth::user()->id)
                            <form method="POST" action="{{route("users.update", $user->id)}}">
                                {{csrf_field()}}
                                {{ method_field('PUT')}}
                                <select name="role">
                                    <option value="{{$user->role}}">{{$user->role_name}}</option>
                                    <option value="1">User</option>
                                    <option value="2">Moderator</option>
                                    <option value="3">Administrator</option>
                                    <option value="4">Super Administrator</option>
                                </select>
                                <button type="submit" class="btn btn-success">Send</button>
                            </form>
                            @endif
                        </td>
                        <td>
                            <form method="POST" action="{{route("users.destroy", $user->id)}}">
                                {{csrf_field()}}
                                {{ method_field('DELETE')}}
                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
            <h2>Clients:</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>CIN</th>
                    <th>Phone number</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    @if($user->role < \App\User::ROLE_MODERATOR)
                    <tr>
                        <th scope="row">{{$user->id}}</th>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->cin}}</td>
                        <td>{{$user->tel}}</td>
                        <td>
                            <form method="POST" action="{{route("users.destroy", $user->id)}}">
                                {{csrf_field()}}
                                {{ method_field('DELETE')}}
                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        </div>
@endsection