routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'VideoSelectionController@chooseNickname')->name('nickname_show');

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::get('/form', 'VideoSelectionController@getFormPart1')->name('form_show');
Route::post('/form', 'VideoSelectionController@getFormPart2')->name('form_send');
Route::get('/win/{id}', 'VideoSelectionController@getFormPart3')->name('winform_show');
Route::post('/win/{id}', 'VideoSelectionController@submitFormPart3')->name('winform_send');
Route::post('/moment', 'VideoSelectionController@chooseMoment')->name('moment_show');
Route::post('/video', 'VideoSelectionController@getVideo')->name('video_get');
Route::get('/video/{id}', 'VideoSelectionController@showVideo')->name('video_show');
Route::get('/video_request', 'VideoSelectionController@getVideoRequest')->name('video_request_show');
Route::get('/preview/{id}', 'VideoSelectionController@getVideoPreview')->name('preview_show');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::resource('/videos', 'VideoController');
Route::resource('/moments', 'MomentController');
Route::resource('/nicknames', 'NicknameController');
Route::resource('/users', 'UserController');

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $fillable = ['nickname', 'gender', 'morning', 'noon', 'night'];

    public function getMorningVideoAttribute()
    {
        return Moment::find($this->morning);
    }
    public function getNoonVideoAttribute()
    {
        return Moment::find($this->noon);
    }
    public function getNightVideoAttribute()
    {
        return Moment::find($this->night);
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Moment;
use App\Nickname;
use App\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = Video::all();
        return view('videos.index', ["videos" => $videos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $nicknames = Nickname::all();
        $morning = Moment::whereCat('morning')->get();
        $noon = Moment::whereCat('noon')->get();
        $night = Moment::whereCat('night')->get();
        return view('videos.create')->with(["nicknames" => $nicknames, "morning" => $morning, "noon" => $noon, "night" => $night]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(is_null($request->file('video')))
            new \Exception("You should select a file");
        $video = Video::firstOrNew(
            [
                'nickname' => $request->nickname,
                'gender' => $request->gender,
                'morning' => $request->morning,
                'noon' => $request->noon,
                'night' => $request->night
            ]
        );
        $video->path = $request->file('video')->store('videos');
        $video->save();

        return redirect()->route('videos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('videos.show')->with('video', Video::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $v = Video::find($id);
        Storage::delete($v->path);
        $v->delete();
        return redirect()->route('videos.index');
    }
}

resources/views/videos/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <form class="col" action="{{route('videos.store')}}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        <div class="form-group row">
            <label class="col-2 col-form-label" for="video">Video file</label>
            <div class="col-10">
                <input type="file" id="video" name="video" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="nickname" class="col-2 col-form-label">Nickname</label>
            <div class="col-10">
                <select name="nickname" id="nickname" class="form-control" required>
                    @foreach($nicknames as $nickname)
                        <option value="{{$nickname->value}}">{{$nickname->value}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="gender" class="col-2 col-form-label">Gender</label>
            <div class="col-10">
                <select name="gender" id="gender" class="form-control" required>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="morning" class="col-2 col-form-label">Morning</label>
            <div class="col-10">
                <select name="morning" id="morning" class="form-control" required>
                    @foreach($morning as $m)
                        <option value="{{$m->id}}">{{$m->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="noon" class="col-2 col-form-label">Noon</label>
            <div class="col-10">
                <select name="noon" id="noon" class="form-control" required>
                    @foreach($noon as $m)
                        <option value="{{$m->id}}">{{$m->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="night" class="col-2 col-form-label">Night</label>
            <div class="col-10">
                <select name="night" id="night" class="form-control" required>
                    @foreach($night as $m)
                        <option value="{{$m->id}}">{{$m->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/videos/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <div class="row">
            @foreach($videos as $video)
                <div class="col-4">
                    <div class="card">
                        <video width="320" height="240" controls>
                            <source src="{{Storage::url($video->path)}}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                        <h4 class="card-title text-center">
                            <span class="badge badge-pill badge-info">{{ucfirst($video->nickname)}}</span>
                            <span class="badge badge-pill badge-warning">{{ucfirst($video->gender)}}</span>
                        </h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{$video->morning_video->name}}</li>
                            <li class="list-group-item">{{$video->noon_video->name}}</li>
                            <li class="list-group-item">{{$video->night_video->name}}</li>
                        </ul>
                        <div class="card-block">
                            <div class="card-text text-center">
                                <div class="btn-group">
                                    <form action="{{route("videos.destroy", $video->id)}}" method="post">
                                        {{csrf_field()}}
                                        {{method_field("DELETE")}}
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Created at: {{$video->created_at}} | Updated at: {{$video->updated_at}}</small>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/videos/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <video width="320" height="240" controls>
                    <source src="{{$video->path}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>                <div class="card-block">
                    <h4 class="card-title">
                        {{$video->name}} <span class="badge badge-pill badge-info">@if($video->watermark) Contains a nickname @endif</span>
                    </h4>
                    <div class="card-text text-center">
                        <div class="btn-group">
                            <a href="{{route('videos.show', $video->id)}}" class="btn btn-success"><i class="fa fa-eye"> Watch</i></a>
                            <button class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</button>
                            <button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Created at: {{$video->created_at}} | Updated at: {{$video->updated_at}}</small>
                </div>
            </div>
        </div>
    </div>
@endsection