routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'VideoSelectionController@chooseNickname')->name('nickname_show');

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::get('/form', 'VideoSelectionController@getFormPart1')->name('form_show');
Route::post('/form', 'VideoSelectionController@getFormPart2')->name('form_send');
Route::get('/win/{id}', 'VideoSelectionController@getFormPart3')->name('winform_show');
Route::post('/win/{id}', 'VideoSelectionController@submitFormPart3')->name('winform_send');
Route::post('/moment', 'VideoSelectionController@chooseMoment')->name('moment_show');
Route::post('/video', 'VideoSelectionController@getVideo')->name('video_get');
Route::get('/video/{id}', 'VideoSelectionController@showVideo')->name('video_show');
Route::get('/video_request', 'VideoSelectionController@getVideoRequest')->name('video_request_show');
Route::get('/preview/{id}', 'VideoSelectionController@getVideoPreview')->name('preview_show');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::resource('/videos', 'VideoController');
Route::resource('/moments', 'MomentController');
Route::resource('/nicknames', 'NicknameController');
Route::resource('/users', 'UserController');

app/Nickname.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Nickname extends Model{

    protected $table = 'nicknames';

}

app/Http/Controllers/NicknameController.php
<?php

namespace App\Http\Controllers;

use App\Nickname;
use Illuminate\Http\Request;

class NicknameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $nicknames = Nickname::all();
        return view('nicknames.index')->with('nicknames', $nicknames);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('nicknames.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $n = new Nickname();
        $n->value = $request->value;
        $n->save();
        return redirect()->route('nicknames.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('nicknames.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return redirect()->route('nicknames.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return redirect()->route('nicknames.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Nickname::destroy($id);
        return redirect()->route('nicknames.index');
    }
}

resources/views/nicknames/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <form class="col" action="{{route('nicknames.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group row">
            <label for="value" class="col-2 col-form-label">Value</label>
            <div class="col-10">
                <input type="text" class="form-control" name="value" id="value" required>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/nicknames/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Value</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($nicknames as $nickname)
                    <tr>
                        <th scope="row">{{$nickname->id}}</th>
                        <td>{{$nickname->value}}</td>
                        <td>
                            <form method="POST" action="{{route("nicknames.destroy", $nickname->id)}}">
                                {{csrf_field()}}
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection